### ISSUE TITLE
Module parse failed: TimeTravel.js

### ISSUE THREAD

**Issue by fbarl** [weaveworks/ui-components#60]
`yarn install && yarn start` throws the following warning, because of which `TimeTravel.js` is not processed and the docs page doesn't get rendered:

```
fbarl@fbarl-XPS-15-9550 ~/Projects/src/github.com/weaveworks/ui-components $ yarn start
yarn run v1.2.1
$ node bin/dev-server

WARNING in ./src/loaders/react-docs.js!./src/components/TimeTravel/TimeTravel.js
Module parse failed: /home/fbarl/Projects/src/github.com/weaveworks/ui-components/src/loaders/react-docs.js!/home/fbarl/Projects/src/github.com/weaveworks/ui-components/src/components/TimeTravel/TimeTravel.js Unexpected token (504:6)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (504:6)
    at Parser.pp$4.raise (/home/fbarl/Projects/src/github.com/weaveworks/ui-components/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/home/fbarl/Projects/src/github.com/weaveworks/ui-components/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp$3.parseExprAtom (/home/fbarl/Projects/src/github.com/weaveworks/ui-components/node_modules/acorn/dist/acorn.js:1822:12)
    at Parser.pp$3.parseExprSubscripts (/home/fbarl/Projects/src/github.com/weaveworks/ui-components/node_modules/acorn/dist/acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (/home/fbarl/Projects/src/github.com/weaveworks/ui-components/node_modules/acorn/dist/acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (/home/fbarl/Projects/src/github.com/weaveworks/ui-components/node_modules/acorn/dist/acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (/home/fbarl/Projects/src/github.com/weaveworks/ui-components/node_modules/acorn/dist/acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (/home/fbarl/Projects/src/github.com/weaveworks/ui-components/node_modules/acorn/dist/acorn.js:1597:21)
    at Parser.pp$3.parseParenAndDistinguishExpression (/home/fbarl/Projects/src/github.com/weaveworks/ui-components/node_modules/acorn/dist/acorn.js:1861:32)
    at Parser.pp$3.parseExprAtom (/home/fbarl/Projects/src/github.com/weaveworks/ui-components/node_modules/acorn/dist/acorn.js:1796:19)
    at Parser.pp$3.parseExprSubscripts (/home/fbarl/Projects/src/github.com/weaveworks/ui-components/node_modules/acorn/dist/acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (/home/fbarl/Projects/src/github.com/weaveworks/ui-components/node_modules/acorn/dist/acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (/home/fbarl/Projects/src/github.com/weaveworks/ui-components/node_modules/acorn/dist/acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (/home/fbarl/Projects/src/github.com/weaveworks/ui-components/node_modules/acorn/dist/acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (/home/fbarl/Projects/src/github.com/weaveworks/ui-components/node_modules/acorn/dist/acorn.js:1597:21)
    at Parser.pp$3.parseExpression (/home/fbarl/Projects/src/github.com/weaveworks/ui-components/node_modules/acorn/dist/acorn.js:1573:21)
 @ ./src/components !./src/loaders/react-docs.js!^((?!test|index|example).)*$
Child html-webpack-plugin for "index.html":
    
webpack: Compiled with warnings.
```

The reported line is ``<g transform={`translate(${position}, 0)`} key={timestamp.format()}>`` in `renderTimestampTick` - it seems as if webpack doesn't know how to parse React DOM (the errors are consistently around that and get dropped when replaced with `return null` inside those functions).

The question is - why only now and why only in `TimeTravel.js`?

@jpellizzari can you reproduce? if yes, any idea what's going on?

**Comment by jpellizzari** [comment]
@fbarl This might be related: https://github.com/weaveworks/ui-components/issues/38
